version: "3.7"

services:
  client:
    ports:
      - 3000:3000
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./client/.env
