version: "3.7"

services:

  client:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./store:/store/
      - ./client:/client/
      - /client/node_modules/
    ports:
      - 3000:3000
