version: "3.7"

services:

  server:
    build:
      context: ./server
    image: fluxcell/server
    restart: unless-stopped
    env_file:
      - ./server/.env

  server-postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
